# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Research',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
