# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, default='my location default', max_length=120, null=True),
        ),
    ]
