# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20170907_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
